#! /bin/bash

sudo pacman -S ansible
sudo pacman -S archey3
sudo pacman -S atop
sudo pacman -S bridge-utils
sudo pacman -S bzip2
sudo pacman -S chromium-pepper-flash
sudo pacman -S cmake
sudo pacman -S cowsay
sudo pacman -S cronie
sudo pacman -S curl
sudo pacman -S dhclient
sudo pacman -S dhcpcd
sudo pacman -S dialog
sudo pacman -S dmidecode
sudo pacman -S dos2unix
sudo pacman -S fabric
sudo pacman -S firefox
sudo pacman -S flac
sudo pacman -S fontconfig
sudo pacman -S gc
sudo pacman -S gcc
sudo pacman -S geany
sudo pacman -S gzip
sudo pacman -S hicolor-icon-theme
sudo pacman -S htop
sudo pacman -S httperf
sudo pacman -S httpie
sudo pacman -S keepassx
sudo pacman -S lsof
sudo pacman -S lua
sudo pacman -S lxc
sudo pacman -S lz4
sudo pacman -S lzo
sudo pacman -S make
sudo pacman -S mc
sudo pacman -S meld
sudo pacman -S mesa-libgl
sudo pacman -S mime-types
sudo pacman -S mkinitcpio
sudo pacman -S mpd
sudo pacman -S mpg123
sudo pacman -S netctl
sudo pacman -S ngrep
sudo pacman -S ntfs-3g
sudo pacman -S openvpn
sudo pacman -S python
sudo pacman -S python-setuptools
sudo pacman -S ruby
sudo pacman -S shotwell
sudo pacman -S siege
sudo pacman -S skype
sudo pacman -S sshfs
sudo pacman -S sublime-text
sudo pacman -S subversion
sudo pacman -S supervisor
sudo pacman -S tmux
sudo pacman -S ttf-hanazono
sudo pacman -S ttf-sazanami
sudo pacman -S ttf-ubuntu-font-family
sudo pacman -S unrar
sudo pacman -S unzip
sudo pacman -S vagrant
sudo pacman -S virtualbox
sudo pacman -S wireshark-cli
sudo pacman -S wireshark-gtk
sudo pacman -S xf86driproto
sudo pacman -S xf86-input-evdev
sudo pacman -S xf86-video-fbdev
sudo pacman -S xf86-video-nouveau
sudo pacman -S xf86vidmodeproto
sudo pacman -S xorg-appres
sudo pacman -S xorg-bdftopcf
sudo pacman -S xorg-fonts-alias
sudo pacman -S xorg-fonts-encodings
sudo pacman -S xorg-fonts-misc
sudo pacman -S xorg-font-util
sudo pacman -S xorg-font-utils
sudo pacman -S xorg-iceauth
sudo pacman -S xorg-mkfontdir
sudo pacman -S xorg-mkfontscale
sudo pacman -S xorg-server-common
sudo pacman -S xorg-server-devel
sudo pacman -S xorg-server-utils
sudo pacman -S xorg-sessreg
sudo pacman -S xorg-setxkbmap
sudo pacman -S xorg-util-macros
sudo pacman -S xorg-xauth
sudo pacman -S xorg-xbacklight
sudo pacman -S xorg-xcmsdb
sudo pacman -S xorg-xgamma
sudo pacman -S xorg-xhost
sudo pacman -S xorg-xinit
sudo pacman -S xorg-xinput
sudo pacman -S xorg-xkbcomp
sudo pacman -S xorg-xmodmap
sudo pacman -S xorg-xrandr
sudo pacman -S xorg-xrdb
sudo pacman -S xorg-xrefresh
sudo pacman -S xorg-xset
sudo pacman -S xorg-xsetroot
sudo pacman -S xscreensaver
sudo pacman -S xz
sudo pacman -S yaourt
sudo pacman -S zathura
sudo pacman -S zathura-djvu
sudo pacman -S zathura-pdf-poppler
sudo pacman -S zip
